import 'package:objectbox/objectbox.dart';

@Entity()
class TodoEntity {
  @Id()
  int id = 0; // generated by ObjectBox

  String task;
  bool isCompleted;

  @Property(type: PropertyType.date)
  DateTime dateCreated;

  TodoEntity({
    required this.task,
    this.isCompleted = false,
    DateTime? dateCreated,
  }) : dateCreated = dateCreated ?? DateTime.now();

  // Necessary mostly for debugging or display
  @override
  String toString() =>
      'TodoEntity{id: $id, task: $task, isCompleted: $isCompleted}';
}
